#include "states.h"

const StateSeed StateSeeds[NumStates] = {
    {"Alabama", 9, 1},
    {"Alaska", 3, 1},
    {"Arizona", 11, 2},
    {"Arkansas", 6, 1},
    {"California", 55, 3},
    {"Colorado", 9, 1},
    {"Connecticut", 7, 1},
    {"Delaware", 3, 1},
    {"Florida", 29, 3},
    {"Georgia", 16, 2},
    {"Hawaii", 4, 1},
    {"Idaho", 4, 1},
    {"Illinois", 20, 2},
    {"Indiana", 11, 2},
    {"Iowa", 7, 1},
    {"Kansas", 6, 1},
    {"Kentucky", 8, 1},
    {"Louisiana", 8, 1},
    {"Maine", 4, 1},
    {"Maryland", 10, 1},
    {"Massachusetts", 11, 2},
    {"Michigan", 16, 2},
    {"Minnesota", 10, 1},
    {"Mississippi", 6, 1},
    {"Missouri", 10, 1},
    {"Montana", 3, 1},
    {"Nebraska", 5, 1},
    {"Nevada", 6, 1},
    {"New Hampshire", 4, 1},
    {"New Jersey", 14, 2},
    {"New Mexico", 5, 1},
    {"New York", 29, 3},
    {"North Carolina", 15, 2},
    {"North Dakota", 3, 1},
    {"Ohio", 18, 2},
    {"Oklahoma", 7, 1},
    {"Oregon", 7, 1},
    {"Pennsylvania", 20, 2},
    {"Rhode Island", 4, 1},
    {"South Carolina", 9, 1},
    {"South Dakota", 3, 1},
    {"Tennessee", 11, 2},
    {"Texas", 38, 3},
    {"Utah", 6, 1},
    {"Vermont", 3, 1},
    {"Virginia", 13, 2},
    {"Washington", 12, 2},
    {"West Virginia", 5, 1},
    {"Wisconsin", 10, 2},
    {"Wyoming", 3, 1},
};
